Advanced
DanilFilikov/Advanced pull request #1
Opened 2023-05-03 13:36 UTC by DanilFilikov

2023-05-03 18:04 UTC, MVlasovD requested changes

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Employer/Employer.java
> +public class Employer {
```suggestion
public class Employee {
```

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Employer/Employer.java
> +
используй ломбок

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Employer/Employer.java
> +    public Employer(String name, int age, int payment, int experience) {
```suggestion
    public Employee(String name, int age, int payment, int experience) {
```

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployerInfo.java
> +public class EmployerInfo {
```suggestion
public class EmployeeInfo {
```

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployerInfo.java
> +    public List<Employer> list3 = List.of(new Employer("Alex", 21, 69000, 3),
```suggestion
    public List<Employee> list3 = List.of(new Employee("Alex", 21, 69000, 3),
```

и так далее

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployerInfo.java
> +    Stream<Employer> stream = list3.stream();
почему list3 ? именно 3

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployerInfo.java
> +        System.out.println(stream.mapToInt(Employer::getPayment).average());
синтаксис стримов исользуй везде

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployerInfo.java
> +        System.out.println(stream.mapToInt(Employer::getPayment).sum());
синтаксис стрима

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployerInfo.java
> +       // System.out.println(stream.filter();
комментарий

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Main.java
> +        System.out.println(collections.getCollection(new ArrayList<>()));
необходимо в большинстве задач написать методы, которые будут принимать разные параметры, и в большинстве из них эти параметры вводим с консоли пользователем (кроме нескольких задач)

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/Main.java
> +        System.out.println(collections.getNumberoftwo(new int[]{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}));
не так

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/StreamTask/CollectionsListof.java
> +    public void getTask2(List<Students> list){
это все нужно делать стримами

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/StreamTask/CollectionsListof.java
> +        stream
```suggestion
        Stream<String> stream = list.stream()
```

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/StreamTask/CollectionsListof.java
> +        stream
```suggestion
        Stream<String> stream = list.stream()
```

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/Sex.java
> +    WOMEN("Женщина");
```suggestion
    MAN,
    WOMEN;
```

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/Students.java
> +
ломбок

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/domain/Ape.java
> +
ломбок

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/domain/Animal.java
> +
ломбок

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/domain/Cat.java
> +
ломбок

2023-05-03 18:04 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/Collections.java
> +
каждую задачу желательно решить в отдельном классе
с вводом с консоли и добавление в начале класса комментариев, что за задача здесь решается

2023-05-04 09:51 UTC, MVlasovD requested changes

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployeeInfo.java
> +                .collect(Collectors.joining(", "));
```suggestion
        String employees = employeeList.stream()
              .map(Employee::toString)
              .collect(Collectors.joining(", "));
```

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployeeInfo.java
> +        Optional<Employee> max = employeeList.stream().max(paymentComparator);
```suggestion
        Optional<Employee> max = employeeList.stream()
               .max(paymentComparator);
```

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployeeInfo.java
> +        if (average.isPresent()) {
это делается не ифом

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployeeInfo.java
> +        System.out.println(employeeList.stream().mapToInt(Employee::getPayment).sum());
```suggestion
        System.out.println(employeeList.stream()
        .mapToInt(Employee::getPayment)
        .sum());
```

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/Main.java
> +        System.out.println(countCouple(new int[]{1, 3, 5, 3, 6, 7, 3, 2, 1, 8, 5}));
зачем это всё?
кроме метода с нахождением пар в массиве, все остальные должны принимать данные с консоли (вводом)

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/StreamTask/CollectionsListOf.java
> +                .map(Students::toString).forEach(System.out::println);
```suggestion
        list.stream()
                .filter(students -> students.getAge() >= 18 && students.getSex() == Sex.MAN && students.getAge() < 27)
                .map(Students::toString)
                .forEach(System.out::println);
```

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/StreamTask/CollectionsListOf.java
> +                || students.getSex() == Sex.WOMEN && students.getAge() >= 18 && students.getAge() < 55).map(Students::toString).forEach(System.out::println);
очень длинная строка

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/EqualPairs.java
> +
```suggestion
```

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/MostRepeatingChar.java
> +public class MostRepeatingChar {
не прогонял весь код через ЧЕКСТАЙЛ

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/Students.java
> +        }
ты же использовал аннотацию

2023-05-04 09:51 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/Сollection.java
> +    public static Set getCollection(ArrayList<Integer> array) {
а если коллекция не интов??

2023-05-04 09:53 UTC, DanilFilikov commented on src/main/java/org/example/Main.java
> +        System.out.println(countCouple(new int[]{1, 3, 5, 3, 6, 7, 3, 2, 1, 8, 5}));
я еще не поменял

2023-05-04 09:54 UTC, DanilFilikov commented on src/main/java/org/example/StringTasks/Students.java
> +        }
Это я уже исправил

2023-05-04 09:54 UTC, DanilFilikov commented on src/main/java/org/example/StringTasks/Сollection.java
> +    public static Set getCollection(ArrayList<Integer> array) {
дженериком сделать?

2023-05-05 17:26 UTC, MVlasovD requested changes

2023-05-05 17:26 UTC, MVlasovD commented on src/main/java/org/example/Employer/EmployeeInfo.java
> +package org.example.Employer;
```suggestion
package org.example.Employee;
```

2023-05-05 17:26 UTC, MVlasovD commented on src/main/java/org/example/Main.java
> +        CollectionsListOf listOF = new CollectionsListOf();
```suggestion
        CollectionsListOf listOf = new CollectionsListOf();
```

2023-05-05 17:26 UTC, MVlasovD commented on src/main/java/org/example/StreamTask/CollectionsListOf.java
> +                .map(Students::toString).forEach(System.out::println);
```suggestion
                .map(Students::toString)
                .forEach(System.out::println);
```

2023-05-05 17:26 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/Collection.java
> +            array.add(in.nextInt());
<Object> но .add(in.nextInt()); инты

2023-05-05 17:26 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/EqualPairs.java
> +
```suggestion
```

2023-05-05 17:26 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/NumberOfTwo.java
> +        System.out.println("\nПодсчитывает количество цифр «2», используемых в десятичной записи целых чисел от 0 до n (включительно)");
длинная строка

2023-05-05 17:26 UTC, MVlasovD commented on src/main/java/org/example/Main.java
> +        EmployeeInfo employerInfo = new EmployeeInfo();
```suggestion
        EmployeeInfo employeeInfo = new EmployeeInfo();
```

2023-05-05 17:26 UTC, MVlasovD commented on src/main/java/org/example/Main.java
> +        System.out.println(getCollection(in));
ты просто все методы подряд выполняешь?

2023-05-07 12:05 UTC, MVlasovD requested changes

2023-05-07 12:05 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/NumberOfTwo.java
> +        System.out.println("Введите кол-во чисел");
кол-во чисел? зачем?

2023-05-07 12:05 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/NumberOfTwo.java
> +    public static int getNumberoftwo(Scanner in) {
ты не понял эту задачу?

2023-05-07 12:05 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/StringComparing.java
> +
желательно ответ получить не true или false, а конкретный "Перестановка" и тд

2023-05-07 15:39 UTC, DanilFilikov commented on src/main/java/org/example/StringTasks/NumberOfTwo.java
> +        System.out.println("Введите кол-во чисел");
Ну в задании от 0 до n. Кол-во чисел и есть n

2023-05-07 15:41 UTC, DanilFilikov commented on src/main/java/org/example/StringTasks/NumberOfTwo.java
> +    public static int getNumberoftwo(Scanner in) {
ну получить все двойки встречающиеся в числах от 0 до n?

2023-05-10 08:38 UTC, MVlasovD requested changes

2023-05-10 08:38 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/Collection.java
> +    public static Set getCollection(Scanner in) {
здесь не нужно никакую коллекцию вводить, нужно добавить в аргументы коллекцию

2023-05-10 08:38 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/NumberOfTwo.java
> +    public static int getNumberoftwo(Scanner in) {
```suggestion
    public static int getNumberOfTwo(Scanner in) {
```

2023-05-10 08:38 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/NumberOfTwo.java
> +        System.out.println("Введите кол-во чисел");
вводишь одну цифру всего, и подсчитываешь кол-во двоек в числах от 0 до этого числа
например, число 22,  от 0 до 22 встречается 6 двоек (**2**, 1**2**, **2**0, **2**1, **22**)

2023-05-10 09:23 UTC, MVlasovD requested changes

2023-05-10 09:23 UTC, MVlasovD commented on src/main/java/org/example/StringTasks/Collection.java
> +    public static Set getCollection(ArrayList<Object> array) {
```suggestion
    public static Set getCollection(List<Object> array) {
```

2023-05-10 09:32 UTC, MVlasovD approved these changes

2023-05-10 09:32 UTC, merged